#!/bin/bash
#
#SBATCH --job-name=biattn
#SBATCH --output=biattn_%j.out
#
#SBATCH --ntasks=4
#SBATCH --gres=gpu:2
#

module load cuda
module load cudnn
module load anaconda

source activate dl

cd bi-att-flow

python -m basic.cli --mode train --noload --num_gpus 2 --len_opt --cluster


